# Generated by Django 4.0.3 on 2022-05-05 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='last_updated',
            field=models.DateField(auto_now=True, verbose_name='last_updated'),
        ),
        migrations.AddField(
            model_name='homeauditmessage',
            name='last_updated',
            field=models.DateField(auto_now=True, verbose_name='last_updated'),
        ),
    ]
