# Generated by Django 4.0.3 on 2022-05-08 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_home_date_added_home_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='album_hash',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='album hash'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='home id'),
        ),
        migrations.AlterField(
            model_name='homeauditmessage',
            name='address_msg',
            field=models.TextField(null=True, verbose_name='address message'),
        ),
        migrations.AlterField(
            model_name='homeauditmessage',
            name='album_msg',
            field=models.TextField(null=True, verbose_name='album message'),
        ),
        migrations.AlterField(
            model_name='homeauditmessage',
            name='apartment_type_msg',
            field=models.TextField(null=True, verbose_name='aparment type message'),
        ),
        migrations.AlterField(
            model_name='homeauditmessage',
            name='price_msg',
            field=models.TextField(null=True, verbose_name='price message'),
        ),
        migrations.AlterField(
            model_name='homeauditmessage',
            name='selling_point_msg',
            field=models.TextField(null=True, verbose_name='selling point message'),
        ),
        migrations.AlterField(
            model_name='homeauditmessage',
            name='short_description_msg',
            field=models.TextField(null=True, verbose_name='short description message'),
        ),
    ]
