# Generated by Django 4.0.3 on 2022-05-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_imagealbum_album_hash_alter_home_home_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagealbum',
            name='album_hash',
        ),
    ]
