# Generated by Django 4.0.3 on 2022-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_imagealbum_album_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('not_reviewed', 'not reviewed'), ('remote_review', 'not reviewed, on-review'), ('updated_for_review', 'not reviewed, on-review'), ('onsite_review', 'not reviewed, on-review'), ('passed_review', 'reviewed'), ('on_sale', 'reviewed, on sale'), ('ongoing', 'reviewed, on sale, ongoing'), ('sold', 'reviewed, sold')], default='not_reviewed', max_length=50, verbose_name='status'),
        ),
    ]
