# Generated by Django 4.0.3 on 2022-05-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_home_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='tags',
            field=models.CharField(default='not reviewed', editable=False, max_length=50, verbose_name='tags'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('remote_review', 'Remote Review'), ('updated_for_review', 'Updated For Review'), ('onsite_review', 'Onsite Review'), ('passed_review', 'Passed Review'), ('on_sale', 'On Sale'), ('ongoing', 'Ongoing'), ('sold', 'Sold')], default='not_reviewed', max_length=50, verbose_name='status'),
        ),
    ]
